apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mattermost-k3d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-09-07T16-13-09Z
          args: ["server", "/data", "--console-address", ":9001"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - secretRef:
                name: minio-credentials
          volumeMounts:
            - name: minio-data
              mountPath: /data
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 30
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-data
