apiVersion: v1
kind: Secret
metadata:
  name: mattermost-credentials
  namespace: mattermost-k3d
type: Opaque
stringData:
  MM_SQLSETTINGS_DATASOURCE: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&connect_timeout=10
  MM_CACHESETTINGS_REDISPASSWORD: redis
  MM_FILESETTINGS_AMAZONS3ACCESSKEYID: minio
  MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: minioadmin
